//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Requests
{
    using Shippo.Models.Components;
    using Shippo.Utils;
    
    public class CreateExampleRequest
    {

        /// <summary>
        /// The number of results to return per page (max 100)
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=header_param")]
        public string? HeaderParam { get; set; }

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public ExampleBody? ExampleBody { get; set; }
    }
}