
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Requests
{
    using Shippo.Models.Components;
    using Shippo.Utils;
    
    public class CreateExampleResponse
    {

        public HTTPMetadata HttpMeta { get; set; } = default!;

        public ExampleResponse? ExampleResponse { get; set; }
        public ExampleSimple? GetExampleResponseSimple()
        {
            if v := this.ExampleResponse; v != nil {
                return v.ExampleSimple;
            }
            return null 
        }
        public ExampleComplex? GetExampleResponseComplex()
        {
            if v := this.ExampleResponse; v != nil {
                return v.ExampleComplex;
            }
            return null 
        }
    }
}