/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;

public class GetExampleRequest {

    /**
     * The number of results to return per page (max 100)
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=header_param")
    private Optional<? extends String> headerParam;

    /**
     * String used to pick a non-default API version to use
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=SHIPPO-API-VERSION")
    private Optional<? extends String> shippoApiVersion;

    @JsonCreator
    public GetExampleRequest(
            Optional<? extends String> headerParam,
            Optional<? extends String> shippoApiVersion) {
        Utils.checkNotNull(headerParam, "headerParam");
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.headerParam = headerParam;
        this.shippoApiVersion = shippoApiVersion;
    }
    
    public GetExampleRequest() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * The number of results to return per page (max 100)
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> headerParam() {
        return (Optional<String>) headerParam;
    }

    /**
     * String used to pick a non-default API version to use
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> shippoApiVersion() {
        return (Optional<String>) shippoApiVersion;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The number of results to return per page (max 100)
     */
    public GetExampleRequest withHeaderParam(String headerParam) {
        Utils.checkNotNull(headerParam, "headerParam");
        this.headerParam = Optional.ofNullable(headerParam);
        return this;
    }

    /**
     * The number of results to return per page (max 100)
     */
    public GetExampleRequest withHeaderParam(Optional<? extends String> headerParam) {
        Utils.checkNotNull(headerParam, "headerParam");
        this.headerParam = headerParam;
        return this;
    }

    /**
     * String used to pick a non-default API version to use
     */
    public GetExampleRequest withShippoApiVersion(String shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = Optional.ofNullable(shippoApiVersion);
        return this;
    }

    /**
     * String used to pick a non-default API version to use
     */
    public GetExampleRequest withShippoApiVersion(Optional<? extends String> shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = shippoApiVersion;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetExampleRequest other = (GetExampleRequest) o;
        return 
            java.util.Objects.deepEquals(this.headerParam, other.headerParam) &&
            java.util.Objects.deepEquals(this.shippoApiVersion, other.shippoApiVersion);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            headerParam,
            shippoApiVersion);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetExampleRequest.class,
                "headerParam", headerParam,
                "shippoApiVersion", shippoApiVersion);
    }
    
    public final static class Builder {
 
        private Optional<? extends String> headerParam = Optional.empty();
 
        private Optional<? extends String> shippoApiVersion = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The number of results to return per page (max 100)
         */
        public Builder headerParam(String headerParam) {
            Utils.checkNotNull(headerParam, "headerParam");
            this.headerParam = Optional.ofNullable(headerParam);
            return this;
        }

        /**
         * The number of results to return per page (max 100)
         */
        public Builder headerParam(Optional<? extends String> headerParam) {
            Utils.checkNotNull(headerParam, "headerParam");
            this.headerParam = headerParam;
            return this;
        }

        /**
         * String used to pick a non-default API version to use
         */
        public Builder shippoApiVersion(String shippoApiVersion) {
            Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
            this.shippoApiVersion = Optional.ofNullable(shippoApiVersion);
            return this;
        }

        /**
         * String used to pick a non-default API version to use
         */
        public Builder shippoApiVersion(Optional<? extends String> shippoApiVersion) {
            Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
            this.shippoApiVersion = shippoApiVersion;
            return this;
        }
        
        public GetExampleRequest build() {
            return new GetExampleRequest(
                headerParam,
                shippoApiVersion);
        }
    }
}

