/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class SDKMethodInterfaces {

    public interface MethodCallGetExample {
        org.openapis.openapi.models.operations.GetExampleResponse getExample(
            Optional<? extends String> headerParam) throws Exception;
    }


    public interface MethodCallCreateExample {
        org.openapis.openapi.models.operations.CreateExampleResponse createExample(
            Optional<? extends String> headerParam,
            Optional<? extends org.openapis.openapi.models.components.ExampleBody> exampleBody) throws Exception;
    }

}
