"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import customsitem as components_customsitem
from ...models.components import customsitembase as components_customsitembase
from typing import Optional


@dataclasses.dataclass
class CreateCustomsItemRequest:
    shippo_api_version: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'SHIPPO-API-VERSION', 'style': 'simple', 'explode': False }})
    r"""String used to pick a non-default API version to use"""
    customs_item_base: Optional[components_customsitembase.CustomsItemBase] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    r"""CustomsItem details."""
    



@dataclasses.dataclass
class CreateCustomsItemResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    customs_item: Optional[components_customsitem.CustomsItem] = dataclasses.field(default=None)
    

