"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import pickup as components_pickup
from ...models.components import pickupbase as components_pickupbase
from typing import Optional


@dataclasses.dataclass
class CreatePickupRequest:
    shippo_api_version: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'SHIPPO-API-VERSION', 'style': 'simple', 'explode': False }})
    r"""String used to pick a non-default API version to use"""
    pickup_base: Optional[components_pickupbase.PickupBase] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    r"""Shippo’s pickups endpoint allows you to schedule pickups with USPS and DHL Express for eligible shipments that you have already created."""
    



@dataclasses.dataclass
class CreatePickupResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    pickup: Optional[components_pickup.Pickup] = dataclasses.field(default=None)
    

