"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import carrieraccount as components_carrieraccount
from ...models.components import connectexistingownupsaccountrequest as components_connectexistingownupsaccountrequest
from typing import Optional


@dataclasses.dataclass
class CreateCarrierAccountRequest:
    shippo_api_version: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'SHIPPO-API-VERSION', 'style': 'simple', 'explode': False }})
    r"""String used to pick a non-default API version to use"""
    connect_existing_own_ups_account_request: Optional[components_connectexistingownupsaccountrequest.ConnectExistingOwnUPSAccountRequest] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    r"""Examples."""
    



@dataclasses.dataclass
class CreateCarrierAccountResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    carrier_account: Optional[components_carrieraccount.CarrierAccount] = dataclasses.field(default=None)
    

