"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import servicegroup as components_servicegroup
from ...models.components import servicegroupcreaterequest as components_servicegroupcreaterequest
from typing import Optional


@dataclasses.dataclass
class CreateServiceGroupRequest:
    shippo_api_version: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'SHIPPO-API-VERSION', 'style': 'simple', 'explode': False }})
    r"""String used to pick a non-default API version to use"""
    service_group_create_request: Optional[components_servicegroupcreaterequest.ServiceGroupCreateRequest] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class CreateServiceGroupResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    service_group: Optional[components_servicegroup.ServiceGroup] = dataclasses.field(default=None)
    

