"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import examplecreaterequest as components_examplecreaterequest
from typing import Optional


@dataclasses.dataclass
class CreateRequest:
    header_param: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'header_param', 'style': 'simple', 'explode': False }})
    r"""The number of results to return per page (max 100)"""
    example_create_request: Optional[components_examplecreaterequest.ExampleCreateRequest] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    

