"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import carrieraccountregistrationstatus as components_carrieraccountregistrationstatus
from enum import Enum
from typing import Optional

class Carrier(str, Enum):
    r"""filter by specific carrier"""
    UPS = 'ups'
    USPS = 'usps'
    CANADA_POST = 'canada_post'


@dataclasses.dataclass
class GetCarrierRegistrationStatusRequest:
    carrier: Carrier = dataclasses.field(metadata={'query_param': { 'field_name': 'carrier', 'style': 'form', 'explode': True }})
    r"""filter by specific carrier"""
    shippo_api_version: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'SHIPPO-API-VERSION', 'style': 'simple', 'explode': False }})
    r"""String used to pick a non-default API version to use"""
    



@dataclasses.dataclass
class GetCarrierRegistrationStatusResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    carrier_account_registration_status: Optional[components_carrieraccountregistrationstatus.CarrierAccountRegistrationStatus] = dataclasses.field(default=None)
    

