"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import customsdeclaration as components_customsdeclaration
from typing import Optional


@dataclasses.dataclass
class GetCustomsDeclarationRequest:
    customs_declaration_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'CustomsDeclarationId', 'style': 'simple', 'explode': False }})
    r"""Object ID of the customs declaration"""
    page: Optional[int] = dataclasses.field(default=1, metadata={'query_param': { 'field_name': 'page', 'style': 'form', 'explode': True }})
    r"""The page number you want to select"""
    shippo_api_version: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'SHIPPO-API-VERSION', 'style': 'simple', 'explode': False }})
    r"""String used to pick a non-default API version to use"""
    



@dataclasses.dataclass
class GetCustomsDeclarationResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    customs_declaration: Optional[components_customsdeclaration.CustomsDeclaration] = dataclasses.field(default=None)
    

