"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import defaultparceltemplate as components_defaultparceltemplate
from ...models.components import defaultparceltemplateupdaterequest as components_defaultparceltemplateupdaterequest
from typing import Optional


@dataclasses.dataclass
class UpdateDefaultParcelTemplateRequest:
    shippo_api_version: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'SHIPPO-API-VERSION', 'style': 'simple', 'explode': False }})
    r"""String used to pick a non-default API version to use"""
    default_parcel_template_update_request: Optional[components_defaultparceltemplateupdaterequest.DefaultParcelTemplateUpdateRequest] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class UpdateDefaultParcelTemplateResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    default_parcel_template: Optional[components_defaultparceltemplate.DefaultParcelTemplate] = dataclasses.field(default=None)
    

