"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from .firstenum import FirstEnum
from .secondenum import SecondEnum
from typing import Union

EnumSet = Union[FirstEnum, SecondEnum]
