"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from typing import Union


class SecondEnum(str, Enum):
    TWO = 'two'


class FirstEnum(str, Enum):
    ONE = 'one'

EnumSet = Union['FirstEnum', 'SecondEnum']
