"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ValueSetEnum(str, Enum):
    r"""Here are the docs for the field that represents a closed value set"""
    VALUE1 = 'Value1'
    VALUE2 = 'Value2'
