/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type CreateExampleRequest = {
    /**
     * The number of results to return per page (max 100)
     */
    headerParam?: string | undefined;
    exampleBody?: components.ExampleBody | undefined;
};

export type CreateExampleResponse = {
    httpMeta: components.HTTPMetadata;
    exampleBody?: components.ExampleBody | undefined;
};

/** @internal */
export namespace CreateExampleRequest$ {
    export const inboundSchema: z.ZodType<CreateExampleRequest, z.ZodTypeDef, unknown> = z
        .object({
            header_param: z.string().optional(),
            ExampleBody: components.ExampleBody$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                header_param: "headerParam",
                ExampleBody: "exampleBody",
            });
        });

    export type Outbound = {
        header_param?: string | undefined;
        ExampleBody?: components.ExampleBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateExampleRequest> = z
        .object({
            headerParam: z.string().optional(),
            exampleBody: components.ExampleBody$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                headerParam: "header_param",
                exampleBody: "ExampleBody",
            });
        });
}

/** @internal */
export namespace CreateExampleResponse$ {
    export const inboundSchema: z.ZodType<CreateExampleResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            ExampleBody: components.ExampleBody$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                ExampleBody: "exampleBody",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        ExampleBody?: components.ExampleBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateExampleResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            exampleBody: components.ExampleBody$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                exampleBody: "ExampleBody",
            });
        });
}
