/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type ListExamplesRequest = {
    /**
     * The number of results to return per page (max 100)
     */
    headerParam?: string | undefined;
};

export type ListExamplesResponse = {
    httpMeta: components.HTTPMetadata;
    exampleListResponse?: Array<components.ExampleBody> | undefined;
};

/** @internal */
export namespace ListExamplesRequest$ {
    export type Inbound = {
        header_param?: string | undefined;
    };

    export const inboundSchema: z.ZodType<ListExamplesRequest, z.ZodTypeDef, Inbound> = z
        .object({
            header_param: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.header_param === undefined ? null : { headerParam: v.header_param }),
            };
        });

    export type Outbound = {
        header_param?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListExamplesRequest> = z
        .object({
            headerParam: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.headerParam === undefined ? null : { header_param: v.headerParam }),
            };
        });
}

/** @internal */
export namespace ListExamplesResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        exampleListResponse?: Array<components.ExampleBody$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<ListExamplesResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            exampleListResponse: z.array(components.ExampleBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.exampleListResponse === undefined
                    ? null
                    : { exampleListResponse: v.exampleListResponse }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        exampleListResponse?: Array<components.ExampleBody$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListExamplesResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            exampleListResponse: z.array(components.ExampleBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.exampleListResponse === undefined
                    ? null
                    : { exampleListResponse: v.exampleListResponse }),
            };
        });
}
