/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class ExampleBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("field")
    private Optional<? extends String> field;

    @JsonCreator
    public ExampleBody(
            @JsonProperty("field") Optional<? extends String> field) {
        Utils.checkNotNull(field, "field");
        this.field = field;
    }
    
    public ExampleBody() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> field() {
        return (Optional<String>) field;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ExampleBody withField(String field) {
        Utils.checkNotNull(field, "field");
        this.field = Optional.ofNullable(field);
        return this;
    }

    public ExampleBody withField(Optional<? extends String> field) {
        Utils.checkNotNull(field, "field");
        this.field = field;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExampleBody other = (ExampleBody) o;
        return 
            java.util.Objects.deepEquals(this.field, other.field);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            field);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ExampleBody.class,
                "field", field);
    }
    
    public final static class Builder {
 
        private Optional<? extends String> field = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder field(String field) {
            Utils.checkNotNull(field, "field");
            this.field = Optional.ofNullable(field);
            return this;
        }

        public Builder field(Optional<? extends String> field) {
            Utils.checkNotNull(field, "field");
            this.field = field;
            return this;
        }
        
        public ExampleBody build() {
            return new ExampleBody(
                field);
        }
    }
}

