/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ExampleBody = {
    field?: string | undefined;
};

/** @internal */
export namespace ExampleBody$ {
    export type Inbound = {
        field?: string | undefined;
    };

    export const inboundSchema: z.ZodType<ExampleBody, z.ZodTypeDef, Inbound> = z
        .object({
            field: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.field === undefined ? null : { field: v.field }),
            };
        });

    export type Outbound = {
        field?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ExampleBody> = z
        .object({
            field: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.field === undefined ? null : { field: v.field }),
            };
        });
}
