/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ExampleBody = {
    field?: string | undefined;
};

/** @internal */
export namespace ExampleBody$ {
    export const inboundSchema: z.ZodType<ExampleBody, z.ZodTypeDef, unknown> = z.object({
        field: z.string().optional(),
    });

    export type Outbound = {
        field?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ExampleBody> = z.object({
        field: z.string().optional(),
    });
}
