/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type WebhookBody = {
    payload?: string | undefined;
};

/** @internal */
export namespace WebhookBody$ {
    export const inboundSchema: z.ZodType<WebhookBody, z.ZodTypeDef, unknown> = z.object({
        payload: z.string().optional(),
    });

    export type Outbound = {
        payload?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WebhookBody> = z.object({
        payload: z.string().optional(),
    });
}
